# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
  
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        cd TaskManager
        pod install --repo-update
      shell: bash

    - name: Force XCode 11.3
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      
    - name: Build
      run: |
        cd TaskManager
        xcodebuild build -workspace TaskManager.xcworkspace -scheme TaskManager clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

    - name: Run tests
      run: |
        cd TaskManager
        xcodebuild test -workspace TaskManager.xcworkspace -scheme TaskManager clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No
